config/routes.rb
Rails.application.routes.draw do

   root 'genres#index'

   get  '/login' => 'sessions#new'
   post '/login' => 'sessions#create'
   get  '/logout'=> 'sessions#destroy'

   resources :genres do
     resources :artists do
       resources :songs
     end
   end

   get '/users/new' => 'users#new'
   post '/users' => 'users#create'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_and_belongs_to_many :genres
  has_many :songs

  validates :artist_name, presence: true
  validates :artist_bio, presence: true
  validates :img_url, presence: true
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  belongs_to :user

  has_and_belongs_to_many :artists

  has_many :songs

  validates :genre_name, presence: true
  validates :genre_description, presence: true
  validates :img_url, presence: true

end

app/models/song.rb
class Song < ActiveRecord::Base

  belongs_to :artist
  belongs_to :genre
  belongs_to :user

  validates :song_name, presence: true
  validates :scloud_embed, presence: true
  validates :song_comment, presence: true
  validates :song_comment, length: { maximum: 150}

  validates_format_of :scloud_embed, :with => /\A(<iframe)/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :genres
  has_many :songs

  validates :user_name, presence: true
  validates :user_name, uniqueness: true

  validates :email, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method(:current_user)

  def authorize
#--->UPDATE THIS LATER!!
    redirect_to '/login' unless current_user
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :authorize

  def new
    @artist = Artist.new
    @genre = Genre.find(params["genre_id"])
  end

  def create
    @artist = Artist.new(artist_params)
    genre_id = Genre.find(params["genre_id"])
    @artist.genres.push(genre_id)
    if @artist.save
      redirect_to genre_path(genre_id)
    else
      render 'new'
    end
  end

  def show
    @artist = Artist.find(params["id"])

    if @artist.songs.nil? || !Song.exists?(params["genre_id"])
      @genre = Genre.find(params["genre_id"])
    else
      current_song = Song.find(params["genre_id"]) #<-- this is a bug.
      genre_id = current_song.genre.id
      @genre = Genre.find(genre_id)
    end
    @songs = Song.where(artist: @artist)
  end


  private
  def artist_params
    params.require(:artist).permit(
      :artist_name,
      :artist_bio,
      :img_url,
    )
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  before_action :authorize, except: [:index,:show]

  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.user_id = current_user.id
    if @genre.save
      redirect_to '/genres'
    else
      render 'new'
    end
  end

  def show
    @genre = Genre.find(params[:id])
    all_artists = Artist.all
    @artists = []
    all_artists.each do |artist|
      if artist.genres.any? {|genre| genre.id == @genre.id }
        @artists << artist
      end
    end
  end

  private
  def genre_params
    params.require(:genre).permit(
      :genre_name,
      :genre_description,
      :img_url,
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(user_name: params[:user_name])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to "/genres"
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/login"
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    @song.artist_id = params["artist_id"]
    @song.genre_id = params["genre_id"]
    @song.user_id = current_user.id
    if @song.save
      redirect_to genre_artist_path(@song.id, params["artist_id"])
    else
      render 'new'
    end
  end

  def edit
    @song = Song.find(params["id"])
  end

  def update
    @song = Song.find(params["id"])
    if @song.update(song_params)
      redirect_to genre_artist_path(@song.id, params["artist_id"])
    else
      render 'edit'
    end
  end

  def destroy
    song = Song.find(params["id"])
    song.destroy
    redirect_to genre_artist_path(params["genre_id"],params["artist_id"])
  end

  private
  def song_params
    params.require(:song).permit(
      :song_name,
      :song_comment,
      :scloud_embed
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to '/login'
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :user_name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/new.html.erb
<div class="row">
  <h3> Add an Artist </h3>
  <div class="six columns offset-by-three">

    <h1>G Stream</h1>
    <% if !@artist.nil? && @artist.errors.any? %>
      <div id="error_message">
        <h5>
          <%= pluralize(@artist.errors.count,"error")%>
          prevented this form from saving
        </h5>
        <ul>
          <% @artist.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <ul>
        <%= form_for @artist, url: {controller: "artists", action: "create", genre_id: @genre.id}, method: :post do |f| %>
          <li>Artist Name: <%=f.text_field :artist_name %></li>
          <li> Image Link: <%=f.text_field :img_url %></li>
          <li> Artist Bio: <%=f.text_area :artist_bio %></li>
          <li><%= f.submit "Create Artist" %></li>
        <% end %>
      </ul>
  </div>
</div>

app/views/artists/show.html.erb
<div class="row">
  
  <div class="eight columns offset-by-two">
    <h1><%=@artist.artist_name%></h1>
    <ul>
      <li><%= image_tag("#{@artist.img_url}")%></li>
      <li><%=@artist.artist_bio%></li>
    </ul>
    <%= link_to "Add a song", new_genre_artist_song_path(@genre.id,@artist.id)%>
  </div>
</div>

<div class="row">
  <div class="eight columns offset-by-two">
    <ul>
      <% @songs.each do |song| %>
        <li><%= "#{song.scloud_embed}".html_safe %></li>
        <li><%= song.song_comment %></li>
        <% if current_user.id == song.user_id %>
          <li><%= link_to "EDIT SONG", edit_genre_artist_song_path(@genre.id,@artist.id,song.id) %>
              <%= link_to "DELETE SONG", genre_artist_song_path(@genre.id,@artist.id,song.id), method: :delete, data: {confirm: "Are you sure?"} %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/genres/index.html.erb
<% @genres.in_groups_of(3).each do |group| %>
  <div class="row">
    <% group.each do |genre| %>
    <% if !genre.nil? %>
        <%= link_to genre_path(genre) do %>
          <div  class="genre-item three columns offset-by-one">
            <ul>
              <li><h4><%= genre.genre_name %></h4></li>
              <li><%= image_tag("#{genre.img_url}", class: "genre_image", size: "150")%></li>
              <li><%= genre.genre_description%></li>
            </ul>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/genres/new.html.erb
<div class = "row">
  <div class ="six columns offset-by-three">
    <h5>Add Genre:</h5>
    <% if !@genre.nil? && @genre.errors.any? %>
      <div id="error_message">
        <h5>
          <%= pluralize(@genre.errors.count,"error")%>
          prevented this article from saving
        </h5>
        <ul>
          <% @genre.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <%end%>

    <ul>
    <%= form_for :genre, url: '/genres', method: :post do |f| %>
      <li>Genre Name: <%= f.text_field :genre_name %></li>
      <li>Image URL: <%= f.text_field :img_url %></li>
      <li>Description: <%= f.text_field :genre_description%></li>
      <li><%= f.submit "Add Genre" %></li>
    </ul>
    <% end %>

  </div>
</div>

app/views/genres/show.html.erb
<div class="row">
  <div class="eight columns offset-by-two">
    <h1><%=@genre.genre_name%></h1>
    <ul>
      <li><%= image_tag("#{@genre.img_url}", size: "400")%></li>
      <li><%=@genre.genre_description%></li>
    </ul>
    <%= button_to "Add an Artist", new_genre_artist_path(@genre), method: :get %>
  </div>
</div>

<div class="row">
  <h2>Genre Artists</h2>
    <% @artists.in_groups_of(3).each do |group| %>
      <div class="row">
        <% group.each do |artist| %>
          <% if !artist.nil? %>
            <%= link_to genre_artist_path(@genre.id,artist.id) do %>
              <div  class="artist-item three columns offset-by-one">
                <ul>
                  <li><%= artist.artist_name %></li>
                  <li><%= image_tag("#{artist.img_url}", size: "200")%></li>
                </ul>
              </div>
            <% end %>
          <% end %>
        <%end%>
      </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GstreamApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Sonsie+One' rel='stylesheet' type='text/css'>
</head>
<body>

  <header>
    <h1><%= link_to "G Stream", root_path %></h1>
    <% if current_user %>
      signed in as <%= current_user.user_name %>
    <% end %>
  </header>

<div class="container">
  <div class = "row">
      <ul class="nav-menu six columns offset-by-three">
        <li><%= link_to_if(!current_user, "Log in", login_path) %></li>
        <li><%= link_to_if(current_user, "Log out", logout_path, data: {confirm: "Are you sure?"} ) %></li>
        <li><%= link_to_if(!current_user, "Sign up", users_new_path) %></li>
        <li><%= link_to "Home", root_path %></li>
      </ul>
  </div>
    <%= yield %>
  <footer>
    <%= button_to "Add a Genre", new_genre_path, method: :get  %>
  </footer>
</div>
</body>

</html>

app/views/songs/edit.html.erb
<div class="row">
  <h3> Edit Song info</h3>
  <div class="six columns offset-by-three">

    <h1>G Stream</h1>
    <% #INCLUDE BECAUSE THE FORM FOR REQUIRES THESE VARIABLES IN CASE OF RE-RENDER %>
    <%  @artist = Artist.find(params["artist_id"]) %>
    <%  @genre = Genre.find(params["genre_id"]) %>

    <% if !@song.nil? && @song.errors.any? %>
      <div id="error_message">
        <h5>
          <%= pluralize(@song.errors.count,"error")%>
          prevented this form from saving
        </h5>
        <ul>
          <% @song.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <ul>
        <%= form_for @song, url: {controller: "songs", action: "update", id: @song.id, genre_id: @genre.id, artist_id: @artist.id } do |f| %>
          <li>Song Title: <%=f.text_field :song_name %></li>
          <li> Your comment: <%=f.text_area :song_comment %></li>
          <li><%= f.submit "Complete Edit" %></li>
        <% end %>
      </ul>
  </div>
</div>

app/views/songs/new.html.erb
<div class="row">
  <h3> Add a Song </h3>
  <div class="six columns offset-by-three">

    <h1>G Stream</h1>
    <% #INCLUDE BECAUSE THE FORM FOR REQUIRES THESE VARIABLES IN CASE OF RE-RENDER %>
    <%  @artist = Artist.find(params["artist_id"]) %>
    <%  @genre = Genre.find(params["genre_id"]) %>

    <% if !@song.nil? && @song.errors.any? %>
      <div id="error_message">
        <h5>
          <%= pluralize(@song.errors.count,"error")%>
          prevented this form from saving
        </h5>
        <ul>
          <% @song.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <ul>
        <%= form_for @song, url: {controller: "songs", action: "create", genre_id: @genre.id, artist_id: @artist.id}, method: :post do |f| %>
          <li>Song Title: <%=f.text_field :song_name %></li>
          <li> Soundcloud embed link: <%=f.text_field :scloud_embed %></li>
          <li> Your comment: <%=f.text_area :song_comment %></li>
          <li><%= f.submit "Add Song" %></li>
        <% end %>
      </ul>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="six columns offset-by-three">
    <h1>G Stream</h1>
    <% if !@user.nil? && @user.errors.any? %>
      <div id="error_message">
        <h5>
          <%= pluralize(@user.errors.count,"error")%>
          prevented this form from saving
        </h5>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <ul>
        <%= form_for @user, url: "/users" do |f| %>
          <li>User Name: <%=f.text_field :user_name %></li>
          <li>    Email: <%=f.text_field :email %></li>
          <li> Password: <%=f.password_field :password %></li>
          <li>Confirm Password: <%= f.password_field :password_confirmation %></li>
          <li><%= f.submit "Register Account" %></li>
        <% end %>
      </ul>
  </div>
</div>